#!/bin/bash

# usage: require_function {function(s) to check...}
# exits if the function doesn't exist
require_function() {
local i
for i ; do
  tempStatus=`type $i >/dev/null 2>&1 && echo true`
  if [ -z "$tempStatus" ]; then
    err "Missing function: $i"
    return 1
  fi
done
}

# usage: require_var {variable(s) to check...}
# exits if the variable doesn't exist
require_var() {
local v i
for i ; do
  v=`eval echo "$"$i`
  if [ -z "$v" ]; then
    v=`eval echo "$"{#$i[*]}`
    if [ "$v" == "0" ]; then
      err "Missing variable: $i"
      stackTrace
      return 1
    fi
  fi
done
}

require_var_or_ask() {
local v new_value var_name="$1"
shift
local description="$1"

v=`eval echo "$"$var_name`
while true; do
  if [ -z "$v" ]; then
    v=`eval echo "$"{#$var_name[*]}`
    if [ "$v" == "0" ]; then
      IFS= read -ep "${description}? ${var_name}=" new_value
      if [ "$new_value" ]; then
        eval "var_name=\"${new_value}\""
        break
      else
        echo "You must enter a valid value to continue."
      fi
    fi
  else
    break
  fi
done
}
