#!/bin/bash

stackTrace() {
count=${#FUNCNAME[*]}
echo "Stack trace:"
for ((n = 1; n < count; n++)) ; do
        p=$((n - 1))
        echo "  ${BASH_SOURCE[$n]} ${FUNCNAME[$n]} ${BASH_LINENO[$p]}"
done
}


